// Generated by hand (no bundler): dsh web client bundles are plain lazy-CJS
// scripts registering a factory on window.__ModuleLoader__. `react` is part of
// the shell's frozen platform module table, so no dsh.client.external is needed.
//
// 这一页把**控制台的全部功能**搬到 dsh 设置里（不再用 iframe 内嵌）。
//
// 与控制器如何做到"两边同步、互不冲突"：
//   - 读：都读同一个桥（模型 / 用量 / 请求 / 签到状态 / 日志）与同一份 .state.json；
//   - 写：账号切换、自动签到开关、体检结果这三类**必须单写者**（控制台的
//     lib/state.mjs 带进程内缓存，插件另写会让它的缓存过期）——因此一律走
//     /workbuddy/console-api/* 透传给控制台，由它写；
//   - 控制台的进程与文件插件一个字都不改。
window.__ModuleLoader__.load({
  id: 'dsh-plugin-workbuddy',
  factory: function (require) {
    'use strict';
    var module = { exports: {} };
    var exports = module.exports;

    var React;
    try {
      React = require('react');
    } catch (error) {
      React = globalThis.React;
      if (!React) throw new Error('dsh-plugin-workbuddy: react is not available in the client module table');
    }
    const h = React.createElement;
    const { useState, useEffect, useCallback, useRef, useMemo } = React;

    const PANEL_HEADERS = { 'x-workbuddy-panel': '1', 'content-type': 'application/json' };
    const CONSOLE_API = '/workbuddy/console-api';

    // ─────────────────────────── 样式 ───────────────────────────
    const CSS = `
/* box-sizing 是防溢出的根：width:100% 的输入件把 padding 算进宽度内 */
.wb-root, .wb-root *{box-sizing:border-box}
.wb-root{display:flex;flex-direction:column;gap:12px;padding:4px 2px 28px;color:var(--dsw-alias-label-primary,light-dark(#0f1115,#f9fafb));font-size:13px;line-height:20px;min-width:0}
.wb-head{display:flex;align-items:flex-start;justify-content:space-between;gap:12px;flex-wrap:wrap}
.wb-title{margin:0;font-size:15px;font-weight:600}
.wb-sub{margin:4px 0 0;color:var(--dsw-alias-label-secondary,light-dark(#61666b,#cfd3d6));font-size:12px;overflow-wrap:anywhere}
.wb-tabs{display:flex;gap:6px;flex-wrap:wrap;border-bottom:.5px solid var(--dsw-alias-border-l2,light-dark(#0000001a,#ffffff1f));padding-bottom:8px}
.wb-tab{appearance:none;border:0;border-radius:999px;padding:5px 12px;font:inherit;font-size:12.5px;cursor:pointer;background:transparent;color:var(--dsw-alias-label-secondary,light-dark(#61666b,#cfd3d6))}
.wb-tab:hover{background:var(--dsw-alias-interactive-bg-hover,light-dark(#2631480f,#ffffff14))}
.wb-tab.on{background:var(--dsw-alias-brand-primary,light-dark(#0f1115,#f9fafb));color:var(--dsw-alias-label-primary-foreground,light-dark(#ffffff,#0f1115))}
.wb-card{background:var(--dsw-alias-bg-module-platform,light-dark(#f9fafb,#353638));border-radius:14px;box-shadow:inset 0 0 0 .5px var(--dsw-alias-border-l2,light-dark(#0000001a,#ffffff1f));padding:14px 16px;min-width:0;overflow:hidden}
.wb-card h3{margin:0 0 10px;font-size:14px;font-weight:600}
.wb-row{display:flex;align-items:center;justify-content:space-between;gap:12px;min-height:30px;min-width:0}
.wb-row+.wb-row{border-top:.5px solid var(--dsw-alias-border-l1,light-dark(#0000000a,#ffffff0f))}
.wb-label{color:var(--dsw-alias-label-secondary,light-dark(#61666b,#cfd3d6));flex:0 0 auto;white-space:nowrap}
.wb-value{flex:1 1 auto;min-width:0;font-variant-numeric:tabular-nums;text-align:right;overflow-wrap:anywhere;word-break:break-word}
/* 胶囊：**不换行**。table-layout:auto 下列宽不会小于 nowrap 内容的宽度，
   所以既不会被压成"使/用/中"三行，也不会像 fixed 布局时那样溢出压住邻居。
   （允许任意断行会让这一列的 min-content 只剩一个汉字宽，列就被压塌了。） */
.wb-pill{display:inline-flex;align-items:center;gap:6px;padding:2px 10px;border-radius:999px;font-size:12px;background:var(--dsw-alias-interactive-bg-hover,light-dark(#2631480f,#ffffff14));max-width:100%;white-space:nowrap}
.wb-dot{width:7px;height:7px;border-radius:50%;background:var(--dsw-alias-label-tertiary,#adb2b8);flex:none}
.wb-dot.ok{background:#2ea043}.wb-dot.warn{background:#d29922}.wb-dot.bad{background:#e5534b}
.wb-actions{display:flex;flex-wrap:wrap;gap:8px;align-items:center;min-width:0}
.wb-btn{appearance:none;border:0;border-radius:9px;padding:6px 12px;font:inherit;font-size:12.5px;cursor:pointer;background:var(--dsw-alias-interactive-bg-hover,light-dark(#2631480f,#ffffff14));color:inherit;text-decoration:none;display:inline-block;flex:none}
.wb-btn:hover{background:var(--dsw-alias-interactive-bg-active,light-dark(#2631481a,#ffffff24))}
.wb-btn.primary{background:var(--dsw-alias-brand-primary,light-dark(#0f1115,#f9fafb));color:var(--dsw-alias-label-primary-foreground,light-dark(#ffffff,#0f1115));font-weight:600}
.wb-btn:disabled{opacity:.5;cursor:default}
.wb-note{color:var(--dsw-alias-label-secondary,light-dark(#61666b,#cfd3d6));font-size:12px;margin:8px 0 0;overflow-wrap:anywhere}
.wb-alert{margin:0 0 10px;padding:9px 12px;border-radius:10px;font-size:12px;background:light-dark(#fff8e1,#3a2f10);color:light-dark(#6b4e00,#f0d38a);overflow-wrap:anywhere}
.wb-alert.bad{background:light-dark(#ffebe9,#3d1d1b);color:light-dark(#a40e26,#ffb3ad)}
/* 表格：**内容驱动宽度**（table-layout:auto）+ 只在词/连字符处换行。
   早先用 fixed + anywhere 换行来"防溢出"，结果 7 列被均分后逐字折断
   （workbudd/y-/desktop.inf/o），nowrap 的胶囊还会溢出单元格压住邻居。
   现在：列宽由内容决定（数字列 nowrap），普通单元格正常断行，只有确实很长
   的文本单元格用 td.wrap（anywhere + 宽度上限）。 */
.wb-table{width:100%;border-collapse:collapse;table-layout:auto;font-size:12px}
.wb-table th,.wb-table td{text-align:left;padding:5px 8px;border-bottom:.5px solid var(--dsw-alias-border-l1,light-dark(#0000000a,#ffffff0f));white-space:normal;word-break:normal;overflow-wrap:break-word;vertical-align:middle}
.wb-table th{color:var(--dsw-alias-label-tertiary,light-dark(#81858c,#adb2b8));font-weight:500;white-space:nowrap}
.wb-table td.num{text-align:right;font-variant-numeric:tabular-nums;white-space:nowrap}
.wb-table td.wrap{overflow-wrap:anywhere;word-break:break-word;min-width:160px;max-width:340px}
/* 操作列（按钮）：**永不换行** —— 否则列被压窄时按钮会竖着堆起来，整行被撑高 */
.wb-table td.wb-actions-col,.wb-table th.wb-actions-col{white-space:nowrap;width:1%;text-align:right}
.wb-table td.wb-actions-col>.wb-btn+.wb-btn{margin-left:6px}
.wb-table tr.bad td{color:light-dark(#a40e26,#ffb3ad)}
.wb-table tr.click{cursor:pointer}
.wb-scroll{overflow:auto;max-height:420px;min-width:0}
/* 状态列里"胶囊 + 切换按钮"并排（两者互斥出现）。允许换行：
   否则 min-content 是两者宽度之和，窄列下会把整表/整行顶宽。 */
.wb-status-cell{display:inline-flex;align-items:center;gap:8px;flex-wrap:wrap;justify-content:flex-end}
/* 模型详情：**紧跟该行展开**（不是挂到表尾），所以样式要像"这张表的一部分" */
.wb-table tr.open td{background:var(--dsw-alias-interactive-bg-hover,light-dark(#2631480f,#ffffff14))}
.wb-detail-row td{background:var(--dsw-alias-interactive-bg-hover,light-dark(#2631480f,#ffffff14));padding:0 8px 12px}
.wb-detail{background:var(--dsw-alias-bg-module-platform,light-dark(#ffffff,#3a3b3d));border-radius:10px;padding:10px 12px;box-shadow:inset 0 0 0 .5px var(--dsw-alias-border-l2,light-dark(#0000001a,#ffffff1f));min-width:0}
.wb-detail-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(200px,1fr));gap:4px 20px}
.wb-detail-item{display:flex;align-items:baseline;justify-content:space-between;gap:10px;min-width:0;font-size:12px}
.wb-detail-item span:first-child{color:var(--dsw-alias-label-secondary,light-dark(#61666b,#cfd3d6));flex:0 0 auto}
.wb-detail-item span:last-child{min-width:0;text-align:right;overflow-wrap:anywhere;font-variant-numeric:tabular-nums}
/* 促销徽章（上游 tags 里的 badge:标签:颜色），渲染成带色小标记 */
.wb-badge{display:inline-block;margin-left:6px;padding:0 6px;border-radius:6px;font-size:11px;line-height:16px;background:light-dark(#00000010,#ffffff1f);border:.5px solid transparent;white-space:nowrap;vertical-align:middle}
/* 账号：每账号一行（列表而非表格）——窄列下不会挤压，宽列下依然整齐 */
.wb-account{padding:9px 2px;border-bottom:.5px solid var(--dsw-alias-border-l1,light-dark(#0000000a,#ffffff0f))}
.wb-account:last-child{border-bottom:0}
.wb-account.bad b{color:light-dark(#a40e26,#ffb3ad)}
.wb-account-head{display:flex;align-items:center;justify-content:space-between;gap:10px;flex-wrap:wrap;min-width:0}
.wb-account-head b{min-width:0;overflow-wrap:anywhere}
.wb-input,.wb-select{background:transparent;border:0;border-bottom:.5px solid var(--dsw-alias-border-l2,light-dark(#0000001a,#ffffff1f));color:inherit;font:inherit;font-size:12.5px;padding:3px 2px;min-width:0;max-width:100%}
.wb-input{width:200px}
/* 下拉框：按钮本体要有实底（截图里曾经是透明的、看着像坏的），
   弹出的 option 必须显式给底色与字色 —— 否则暗色主题下浅字落在白底上，几乎看不见 */
.wb-select{background:var(--dsw-alias-bg-module-platform,light-dark(#ffffff,#3a3b3d));color:var(--dsw-alias-label-primary,light-dark(#0f1115,#f9fafb));border:.5px solid var(--dsw-alias-border-l2,light-dark(#0000001f,#ffffff2e));border-radius:8px;padding:4px 8px;cursor:pointer}
.wb-select:hover{background:var(--dsw-alias-interactive-bg-hover,light-dark(#2631480f,#ffffff14))}
.wb-select option{background:light-dark(#ffffff,#3a3b3d);color:light-dark(#0f1115,#f9fafb)}
.wb-check{display:inline-flex;align-items:center;gap:5px;font-size:12.5px;color:var(--dsw-alias-label-secondary,light-dark(#61666b,#cfd3d6));white-space:nowrap}
.wb-log{margin:0;max-height:360px;overflow:auto;font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;font-size:11.5px;line-height:17px;white-space:pre-wrap;overflow-wrap:anywhere;color:var(--dsw-alias-label-secondary,light-dark(#61666b,#cfd3d6))}
.wb-chat{display:flex;flex-direction:column;gap:8px;max-height:420px;overflow:auto;padding:4px 2px;min-width:0}
.wb-msg{padding:8px 11px;border-radius:11px;font-size:12.5px;white-space:pre-wrap;overflow-wrap:anywhere;max-width:88%}
.wb-msg.user{align-self:flex-end;background:var(--dsw-alias-brand-primary,light-dark(#0f1115,#f9fafb));color:var(--dsw-alias-label-primary-foreground,light-dark(#ffffff,#0f1115))}
.wb-msg.assistant{align-self:flex-start;background:var(--dsw-alias-interactive-bg-hover,light-dark(#2631480f,#ffffff14))}
.wb-msg.meta{align-self:center;background:transparent;color:var(--dsw-alias-label-tertiary,light-dark(#81858c,#adb2b8));font-size:11.5px;padding:0}
.wb-msg-meta{display:block;margin-top:6px;padding-top:5px;border-top:.5px solid var(--dsw-alias-border-l1,light-dark(#00000014,#ffffff1a));color:var(--dsw-alias-label-tertiary,light-dark(#81858c,#adb2b8));font-size:11px;font-variant-numeric:tabular-nums}
.wb-textarea{display:block;width:100%;max-width:100%;min-height:64px;resize:vertical;background:var(--dsw-alias-interactive-bg-hover,light-dark(#2631480f,#ffffff14));border:0;border-radius:10px;color:inherit;font:inherit;font-size:12.5px;padding:8px 10px;margin:0}
.wb-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(140px,1fr));gap:10px}
.wb-metric{background:var(--dsw-alias-interactive-bg-hover,light-dark(#2631480f,#ffffff14));border-radius:11px;padding:10px 12px;min-width:0}
.wb-metric b{display:block;font-size:17px;font-weight:600;margin-top:2px;overflow-wrap:anywhere}
.wb-metric span{color:var(--dsw-alias-label-secondary,light-dark(#61666b,#cfd3d6));font-size:11.5px}
.wb-bar{height:6px;border-radius:3px;background:var(--dsw-alias-interactive-bg-active,light-dark(#2631481a,#ffffff24));overflow:hidden;margin-top:6px}
.wb-bar i{display:block;height:100%;background:#2ea043}
.wb-bar i.warn{background:#d29922}
.wb-bar i.bad{background:#e5534b}
/* 积分卡：概览页的头条指标，单独一张卡 + 大号数字 */
.wb-quota{background:linear-gradient(180deg,light-dark(#ffffff,#3b3c3f),var(--dsw-alias-bg-module-platform,light-dark(#f9fafb,#353638)))}
.wb-quota-head{display:flex;align-items:flex-start;justify-content:space-between;gap:12px;flex-wrap:wrap}
.wb-quota-label{color:var(--dsw-alias-label-secondary,light-dark(#61666b,#cfd3d6));font-size:12px;letter-spacing:.04em}
.wb-quota-total{font-size:38px;line-height:1.15;font-weight:700;font-variant-numeric:tabular-nums;margin-top:2px;overflow-wrap:anywhere}
.wb-quota-pkgs{display:grid;grid-template-columns:repeat(auto-fit,minmax(210px,1fr));gap:10px 18px;margin-top:14px}
.wb-quota-pkg{min-width:0}
.wb-quota-pkg-head{display:flex;align-items:baseline;justify-content:space-between;gap:8px;min-width:0}
.wb-quota-pkg-name{font-size:12px;min-width:0;overflow-wrap:anywhere}
.wb-quota-pkg-num{font-size:12px;font-variant-numeric:tabular-nums;color:var(--dsw-alias-label-secondary,light-dark(#61666b,#cfd3d6));white-space:nowrap}
.wb-chart{width:100%;max-width:100%;height:auto;display:block}
`;

    const styleId = 'dsh-plugin-workbuddy-style';
    function insertStyles() {
      if (document.getElementById(styleId)) return () => {};
      const el = document.createElement('style');
      el.id = styleId;
      el.textContent = CSS;
      document.head.appendChild(el);
      return () => { try { el.remove(); } catch (e) { /* ignore */ } };
    }

    // ─────────────────────────── 基础请求 ───────────────────────────
    const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

    /**
     * GET 一个 JSON 接口。
     *
     * **404 要重试**：dsh 的 Web 兜底处理器在插件还没把路由挂上时（应用刚启动、
     * 或插件重载中）会对任何未命中的路径回 404。刷新页面的瞬间正好撞上这个窗口，
     * 面板就会挂着一个红字 HTTP 404 —— 而下一个轮询可能要 60~120 秒以后。
     * 所以 404 单独快速重试，把"启动窗口"消化掉。
     */
    async function getJson(path, options) {
      const opts = options || {};
      const retries = opts.retries === undefined ? 3 : opts.retries;
      for (let attempt = 0; ; attempt += 1) {
        const res = await fetch(path, { cache: 'no-store' });
        const text = await res.text();
        let data;
        try { data = JSON.parse(text); } catch (e) { data = { ok: false, error: text.slice(0, 200) }; }
        if (res.status === 404 && attempt < retries) {
          await sleep(500 * (attempt + 1)); // 0.5s → 1s → 1.5s
          continue;
        }
        return { status: res.status, data };
      }
    }
    async function postJson(path, body, method) {
      const res = await fetch(path, { method: method || 'POST', headers: PANEL_HEADERS, body: body === undefined ? undefined : JSON.stringify(body), cache: 'no-store' });
      const text = await res.text();
      let data;
      try { data = JSON.parse(text); } catch (e) { data = { ok: false, error: text.slice(0, 200) }; }
      return { status: res.status, data };
    }

    /**
     * 轮询式取数；enabled=false 时完全不请求（面板切走就停）。
     *
     * 两处恢复机制，避免"一次失败挂很久"：
     *   1. 404 由 getJson 自己快速重试（插件启动窗口）；
     *   2. 任何失败（含 4xx/5xx）额外排一次 4 秒后的重试 —— 不然按配置的
     *      轮询间隔（用量 60s、模型 120s）用户要盯着红字等一两分钟。
     */
    function useJson(path, options) {
      const opts = options || {};
      const [state, setState] = useState({ data: null, error: '', status: 0, loading: true });
      const alive = useRef(true);
      const retryTimer = useRef(null);
      const reload = useCallback(async (overridePath) => {
        try {
          const { status, data } = await getJson(overridePath || path);
          if (!alive.current) return;
          const failed = status >= 400 || data?.ok === false;
          const message = failed
            ? (status === 404 ? '插件还没就绪（HTTP 404），正在自动重试…' : String(data?.error || `HTTP ${status}`))
            : '';
          setState({ data: failed && status === 404 ? null : data, status, error: message, loading: false });
          if (failed && alive.current && !retryTimer.current) {
            retryTimer.current = setTimeout(() => { retryTimer.current = null; reload(); }, 4000);
          }
        } catch (error) {
          if (alive.current) setState({ data: null, status: 0, error: String(error?.message || error), loading: false });
          if (alive.current && !retryTimer.current) {
            retryTimer.current = setTimeout(() => { retryTimer.current = null; reload(); }, 4000);
          }
        }
      }, [path]);
      useEffect(() => {
        alive.current = true;
        if (opts.enabled === false) return undefined;
        setState((s) => ({ ...s, loading: true }));
        reload();
        const timer = opts.interval ? setInterval(reload, opts.interval) : null;
        return () => {
          alive.current = false;
          if (timer) clearInterval(timer);
          if (retryTimer.current) { clearTimeout(retryTimer.current); retryTimer.current = null; }
        };
      }, [reload, opts.interval, opts.enabled]);
      return { data: state.data, error: state.error, status: state.status, loading: state.loading, reload };
    }

    // ─────────────────────────── 格式化 / 导出 ───────────────────────────
    const fmtInt = (n) => (typeof n === 'number' && isFinite(n) ? n.toLocaleString('zh-CN') : '—');
    const fmtTokens = (n) => {
      const v = Number(n) || 0;
      if (v >= 1_000_000) return (v / 1_000_000).toFixed(1) + 'M';
      if (v >= 1000) return (v / 1000).toFixed(1) + 'k';
      return String(v);
    };
    function fmtDuration(ms) {
      const minutes = Math.floor((Number(ms) || 0) / 60000);
      if (minutes < 60) return minutes + ' 分';
      const hours = Math.floor(minutes / 60);
      if (hours < 48) return hours + ' 小时 ' + (minutes % 60) + ' 分';
      return Math.floor(hours / 24) + ' 天 ' + (hours % 24) + ' 小时';
    }
    function fmtRemaining(iso) {
      if (!iso) return '—';
      const ms = new Date(iso).getTime() - Date.now();
      if (!isFinite(ms)) return '—';
      return ms <= 0 ? '已过期' : '约 ' + fmtDuration(ms);
    }
    function fmtTime(ts) {
      if (!ts) return '—';
      const d = new Date(Number(ts));
      return d.toLocaleString('zh-CN', { hour12: false });
    }
    function fmtClock(ts) {
      if (!ts) return '—';
      return new Date(Number(ts)).toLocaleTimeString('zh-CN', { hour12: false });
    }
    function fmtAgo(ts) {
      const ms = Date.now() - Number(ts || 0);
      if (!isFinite(ms) || ms < 0) return '—';
      if (ms < 60000) return Math.round(ms / 1000) + ' 秒前';
      if (ms < 3600000) return Math.round(ms / 60000) + ' 分钟前';
      if (ms < 86400000) return Math.round(ms / 3600000) + ' 小时前';
      return Math.round(ms / 86400000) + ' 天前';
    }
    function downloadCsv(name, header, rows) {
      const esc = (v) => {
        const s = v === null || v === undefined ? '' : String(v);
        return /[",\n]/.test(s) ? '"' + s.replace(/"/g, '""') + '"' : s;
      };
      const text = '\ufeff' + [header, ...rows].map((r) => r.map(esc).join(',')).join('\n') + '\n';
      try {
        const url = URL.createObjectURL(new Blob([text], { type: 'text/csv;charset=utf-8' }));
        const a = document.createElement('a');
        a.href = url;
        a.download = name;
        document.body.appendChild(a);
        a.click();
        a.remove();
        setTimeout(() => URL.revokeObjectURL(url), 4000);
      } catch (e) { /* 下载被拦时至少不炸页面 */ }
    }
    function copyText(text) {
      try { navigator.clipboard.writeText(text); return true; } catch (e) { return false; }
    }

    // ─────────────────────────── 通用组件 ───────────────────────────
    /**
     * 控制台域的取数钩子。
     *
     * 三种"不可用"要分清，提示各不相同：
     *   - 503：控制台没跑 → 「启动控制台」按钮；
     *   - 404：宿主端还是旧构建（没有透传路由）→ 「重启 dsh」；
     *   - 其它：如实显示错误文本。
     * 控制台不可用时不轮询（避免对 404 端点每 30 秒空转一次）。
     */
    function useConsoleApi(path, options) {
      const opts = options || {};
      const first = useJson(path, opts);
      const [availability, setAvailability] = useState({ state: 'checking' });
      useEffect(() => {
        if (first.status === 503) setAvailability({ state: 'console-down' });
        else if (first.status === 404) setAvailability({ state: 'stale-host' });
        else if (first.status === 0 && first.error) setAvailability({ state: 'error', error: first.error });
        else if (first.status >= 200 && first.status < 500) setAvailability({ state: 'ok' });
      }, [first.status, first.error]);
      const probeConsole = useCallback(async () => {
        try {
          const res = await fetch('/workbuddy/console', { cache: 'no-store' });
          const data = await res.json().catch(() => ({}));
          setAvailability(data.state === 'running' ? { state: 'ok' } : { state: 'console-down' });
        } catch (e) { setAvailability({ state: 'error', error: String(e && e.message ? e.message : e) }); }
      }, []);
      return { ...first, availability, probeConsole };
    }

    /** 控制台域功能不可用时的统一可行动提示。 */
    function ConsoleGate(props) {
      const { availability, onStartConsole, onProbe, busy, feature } = props;
      if (availability.state === 'ok') return null;
      if (availability.state === 'stale-host') {
        return h(Card, { title: feature },
          h(Alert, { bad: true },
            '这一页的新代码已经加载，但 dsh 进程里的宿主端还是旧构建（透传接口不存在，HTTP 404）。'
            + '宿主端改动要重启一次 DeepSeek Harness 才生效 —— 完全退出（托盘退出）再打开即可。'),
          h(Btn, { onClick: onProbe }, '再查一次'));
      }
      if (availability.state === 'console-down') {
        return h(Card, { title: feature },
          h(Alert, null, '这项功能由控制台提供（它保证 .state.json 只有一个写者，两边才不会不同步）。'),
          h(Btn, { primary: true, disabled: busy, onClick: onStartConsole }, '启动控制台'));
      }
      if (availability.state === 'error') {
        return h(Card, { title: feature }, h(Alert, { bad: true }, availability.error));
      }
      return h(Card, { title: feature }, h('p', { className: 'wb-note' }, '正在检测控制台…'));
    }

    function Card(props) {
      return h('div', { className: 'wb-card' + (props.className ? ' ' + props.className : '') }, props.title ? h('h3', null, props.title) : null, props.children);
    }
    function Row(props) {
      return h('div', { className: 'wb-row' },
        h('span', { className: 'wb-label' }, props.label),
        h('span', { className: 'wb-value' }, props.children));
    }
    function Pill(props) {
      return h('span', { className: 'wb-pill' }, h('span', { className: 'wb-dot ' + (props.tone || '') }), props.text);
    }
    function Btn(props) {
      return h('button', {
        className: 'wb-btn' + (props.primary ? ' primary' : ''),
        disabled: props.disabled,
        onClick: props.onClick,
        title: props.title,
      }, props.children);
    }
    function Alert(props) {
      return h('p', { className: 'wb-alert' + (props.bad ? ' bad' : '') }, props.children);
    }
    function LineChart(props) {
      const points = props.points || [];
      if (points.length < 2) return h('p', { className: 'wb-note' }, '数据点不足，画不出趋势。');
      const width = 720;
      const height = 170;
      const pad = { l: 8, r: 8, t: 10, b: 18 };
      const max = Math.max(...points.map((p) => p.value), 1);
      const stepX = (width - pad.l - pad.r) / (points.length - 1);
      const y = (v) => pad.t + (height - pad.t - pad.b) * (1 - v / max);
      const line = points.map((p, i) => `${i === 0 ? 'M' : 'L'}${(pad.l + i * stepX).toFixed(1)},${y(p.value).toFixed(1)}`).join(' ');
      const area = `${line} L${(pad.l + (points.length - 1) * stepX).toFixed(1)},${y(0)} L${pad.l},${y(0)} Z`;
      const every = Math.ceil(points.length / 8);
      return h('svg', { viewBox: `0 0 ${width} ${height}`, style: { width: '100%', height: 'auto', display: 'block' } },
        h('path', { d: area, fill: 'var(--dsw-alias-interactive-bg-hover, rgba(120,140,180,.18))' }),
        h('path', { d: line, fill: 'none', stroke: 'var(--dsw-alias-brand-primary, #4f6bd8)', 'stroke-width': 2 }),
        ...points.map((p, i) => h('circle', { key: 'c' + i, cx: pad.l + i * stepX, cy: y(p.value), r: 2.5, fill: 'var(--dsw-alias-brand-primary, #4f6bd8)' },
          h('title', null, `${p.label}：${p.value}`))),
        ...points.map((p, i) => (i % every === 0 || i === points.length - 1)
          ? h('text', { key: 't' + i, x: pad.l + i * stepX, y: height - 4, fontSize: 10, textAnchor: 'middle', fill: 'var(--dsw-alias-label-tertiary, #888)' }, p.label)
          : null),
        h('text', { x: pad.l, y: pad.t + 8, fontSize: 10, fill: 'var(--dsw-alias-label-tertiary, #888)' }, String(max)));
    }

    // ─────────────────────────── 概览 ───────────────────────────
    function OverviewPanel(props) {
      const { status, onAct, busy, reload, onOpenTab } = props;
      const bridge = status?.bridge || {};
      const health = bridge.health;
      const state = bridge.state || 'unknown';
      const tone = state === 'running' ? 'ok' : (state === 'stopped' || state === 'degraded') ? 'bad' : 'warn';
      const text = state === 'running' ? '运行中'
        : state === 'stopped' ? '未运行'
          : state === 'degraded' ? '凭据异常'
            : state === 'unauthorized' ? '令牌不符'
              : state === 'foreign' ? '端口被占' : state;
      const con = status?.console || {};
      // 最近失败：本地账本，很便宜；与控制台顶部提示条同一条口径
      const { data: recent } = useJson('/workbuddy/requests?limit=20', { interval: 15000 });
      // 签到状态也自己问一次（宿主快照里那份是后台刷新的，可能还没值）；
      // 5 分钟一次足够，且这个接口会打到上游，不宜勤问。
      const { data: checkinData } = useJson('/workbuddy/checkin', { interval: 300000 });
      const failedRecent = (recent?.requests || []).filter((r) => !r.ok);
      const checkinStatus = (checkinData?.status ? checkinData.status : checkinData) || status?.checkin?.status;
      const alerts = [];
      if (state === 'degraded') {
        // 桥活着但登录凭据读不出来（最常见：WorkBuddy 登录过期）——不许说成"桥没跑"
        alerts.push({ tone: 'bad', text: '桥在跑，但读不出登录凭据：' + (bridge.error || '未知原因'), action: 'restart' });
      } else if (state === 'unauthorized') {
        alerts.push({ tone: 'bad', text: bridge.error || '端口上的桥与本插件的本地令牌不一致', action: 'restart' });
      } else if (state === 'foreign') {
        alerts.push({ tone: 'bad', text: bridge.error || '端口被别的服务占用了', action: 'restart' });
      } else if (state !== 'running') {
        alerts.push({ tone: 'bad', text: '桥没有在运行 —— 模型调用会失败', action: 'start' });
      }
      if (state === 'degraded') {
        alerts.push({ tone: 'warn', text: '修法：打开 WorkBuddy 桌面端重新登录一次；不行再看 诊断 页的「登录文件 / 凭据解密」两项' });
      }
      if (health?.auth?.expired) alerts.push({ tone: 'bad', text: '登录令牌已过期（桥会在下次请求时尝试续期）', action: 'restart' });
      else if (health?.auth?.expiresAt && new Date(health.auth.expiresAt).getTime() - Date.now() < 7 * 86400000) {
        alerts.push({ tone: 'warn', text: '令牌不到 7 天到期，建议重新登录 WorkBuddy 桌面端' });
      }
      if (!status?.route?.registered) alerts.push({ tone: 'bad', text: '原生模型路由未注册：' + (status?.route?.error || '未知原因') });
      if (failedRecent.length) alerts.push({ tone: 'warn', text: `最近请求里有 ${failedRecent.length} 条失败`, action: 'requests' });
      if (checkinStatus && checkinStatus.todayCheckedIn === false && checkinStatus.active !== false) {
        alerts.push({ tone: 'warn', text: '今日还没签到', action: 'checkin' });
      }
      if (status?.legacy?.found) alerts.push({ tone: 'warn', text: '检测到旧的 llm-pi-ai 路由，与插件撞名，建议清理', action: 'cleanup' });
      // 控制台 /api/overview 的 routeLive 同样是迁移前口径（只认 settings.yaml /
      // profile patch），原生路由它看不见 —— 原生路由已注册时不作为问题提示。

      const ACTION_LABEL = { start: '启动桥', restart: '重启桥', cleanup: '清理旧路由', requests: '查看失败', checkin: '去签到' };
      const alertAction = (action) => {
        if (action === 'requests' || action === 'checkin') onOpenTab(action);
        else onAct(action);
      };

      const quota = status?.quota;
      const report = () => {
        const lines = [
          'WorkBuddy 中转诊断报告',
          '时间：' + fmtTime(Date.now()),
          '桥：' + state + (health ? ` pid=${health.pid} uptime=${fmtDuration(health.uptimeMs)}` : '') + ' ' + (status?.config?.bridgeUrl || ''),
          '账号：' + (health?.auth?.userId || '(未知)') + ' 令牌剩余 ' + fmtRemaining(health?.auth?.expiresAt),
          '目录：' + (status?.directory || []).length + ' 个模型',
          '路由：' + (status?.route?.registered ? '已注册 provider=' + status.route.provider : '未注册 ' + (status?.route?.error || '')),
          '控制台：' + (con.state || '?') + ' ' + (con.url || ''),
          '积分：' + (quota?.total !== undefined ? quota.total : '(未读取)'),
          '检出目录：' + (status?.config?.projectRoot || ''),
        ];
        copyText(lines.join('\n'));
      };

      return h('div', { style: { display: 'flex', flexDirection: 'column', gap: '12px' } },
        // 积分卡放在最前：这是大家真正在意的东西，值得单独一张卡 + 大号数字
        h(QuotaCard, { status, reload, busy, onOpenTab }),

        alerts.length
          ? h('div', { className: 'wb-card' },
            h('h3', null, '需要你动手'),
            ...alerts.map((a, i) => h('div', { key: i, className: 'wb-row' },
              h('span', { style: { minWidth: 0 } }, h(Pill, { tone: a.tone, text: a.text })),
              a.action ? h(Btn, { disabled: busy, onClick: () => alertAction(a.action) }, ACTION_LABEL[a.action] || '处理') : null)))
          : h(Card, { title: '需要你动手' }, h('p', { className: 'wb-note', style: { margin: 0 } }, '没有待办事项。')),

        h(Card, { title: '状态' },
          h(Row, { label: '本地桥' }, h(Pill, { tone, text })),
          health ? h(Row, { label: '进程 / 地址' }, 'pid ' + health.pid + ' · ' + (status?.config?.bridgeUrl || '') + '/v1') : null,
          health ? h(Row, { label: '已运行' }, fmtDuration(health.uptimeMs)) : null,
          health?.auth ? h(Row, { label: '登录账号' }, health.auth.userId || '(未识别)') : null,
          health?.auth ? h(Row, { label: '令牌剩余' }, fmtRemaining(health.auth.expiresAt)) : null,
          h(Row, { label: '上游端点' }, health?.auth?.endpoint || '—'),
          h(Row, { label: '可用模型' }, fmtInt((status?.directory || []).length) + ' 个' + (status?.sampleModel ? '，推荐 ' + status.sampleModel : '')),
          h(Row, { label: 'dsh 原生路由' }, status?.route?.registered ? '已注册 provider=' + status.route.provider + (status.route.fallback ? '（兜底）' : '') : '未注册'),
          h(Row, { label: '数据控制台' }, h(Pill, { tone: con.state === 'running' ? 'ok' : 'bad', text: con.state === 'running' ? '运行中' : (con.state || '未运行') })),
          status?.config?.projectRoot ? h(Row, { label: '检出目录' }, status.config.projectRoot) : null),

        h(Card, { title: '操作' },
          h('div', { className: 'wb-actions' },
            h(Btn, { primary: true, disabled: busy, onClick: () => onAct('start') }, '启动桥'),
            h(Btn, { disabled: busy, onClick: () => onAct('restart') }, '重启桥'),
            h(Btn, { disabled: busy, onClick: () => onAct('stop') }, '停止桥'),
            h(Btn, { disabled: busy, onClick: () => onAct('console-start') }, '启动控制台'),
            h(Btn, { disabled: busy, onClick: () => reload() }, '刷新状态'),
            h(Btn, { onClick: () => onOpenTab('diagnose') }, '去诊断 →'),
            h(Btn, { disabled: busy, onClick: report }, '复制诊断报告'),
            h(Btn, { onClick: () => copyText(status?.config?.bridgeUrl + '/v1') }, '复制桥地址'))));
    }

    /**
     * 促销徽章：新宿主直接给结构化的 `badges`；旧宿主只在 `tags` 里塞
     * `badge:标签:#颜色`。这里两种都认 —— 不然重启 dsh 之前徽章就看不到。
     */
    function badgesOf(m) {
      if (Array.isArray(m?.badges)) return m.badges;
      const out = [];
      for (const raw of m?.tags || []) {
        const match = /^badge:(.+?)(?::(#[0-9a-fA-F]{3,8}))?$/.exec(String(raw));
        if (match) out.push({ label: match[1], color: match[2] || null });
      }
      if (m?.badge && !out.some((b) => b.label === m.badge)) out.push({ label: String(m.badge), color: null });
      return out;
    }
    /** 干净的标签（剔掉 badge: 规格）。 */
    function tagsOf(m) {
      return (m?.tags || []).map(String).filter((t) => !/^badge:/.test(t));
    }

    /** 详情里的一行「标签 / 值」（用网格排，比 Row 在宽表格里更紧凑）。 */
    function DetailItem(props) {
      return h('div', { className: 'wb-detail-item', title: props.hint || undefined },
        h('span', null, props.label),
        h('span', { title: String(props.value ?? '') }, props.value ?? '—'));
    }

    // ─────────────────────────── 积分卡 ───────────────────────────
    /**
     * 独立的积分卡：大号余额 + 套餐进度 + 刷新。
     *
     * 刷新走 `POST /workbuddy/quota`（宿主端强制重读上游），因为状态接口对积分有
     * 120 秒缓存 —— 不然点了"刷新"看不到变化，等于骗人。
     * 同名套餐合并计数：上游会把同一档权益拆成多条（本机实测 4 条同名 100/100），
     * 逐条列出来只是噪音。
     */
    function QuotaCard({ status, reload, busy, onOpenTab }) {
      const [refreshing, setRefreshing] = useState(false);
      const [message, setMessage] = useState('');
      const quota = status?.quota;
      const error = status?.quotaError || (quota && quota.ok === false ? String(quota.error || '读取失败') : '');
      const total = typeof quota?.total === 'number' ? quota.total : null;

      const packages = useMemo(() => {
        const byName = new Map();
        for (const p of quota?.packages || []) {
          const key = p.name || '(未命名套餐)';
          const prev = byName.get(key);
          if (prev) {
            prev.remain += Number(p.remain) || 0;
            prev.size += Number(p.size) || 0;
            prev.count += 1;
            if (p.expiresAt && !prev.expiresAt) prev.expiresAt = p.expiresAt;
          } else {
            byName.set(key, {
              name: key,
              remain: Number(p.remain) || 0,
              size: Number(p.size) || 0,
              count: 1,
              monthly: p.monthly === true,
              expiresAt: p.expiresAt || null,
            });
          }
        }
        return [...byName.values()].sort((a, b) => b.remain - a.remain);
      }, [quota]);

      const refreshQuota = async () => {
        setRefreshing(true);
        setMessage('');
        const res = await postJson('/workbuddy/quota', {});
        setRefreshing(false);
        if (res.status === 404) {
          // 宿主端还是旧构建（没有 /workbuddy/quota）：退回刷新状态。
          // 积分这时走 120 秒缓存，重启 dsh 后才能"立即重读上游"。
          setMessage('宿主端还是旧构建：已按缓存刷新（重启一次 dsh 后，「刷新积分」可直接重读上游）。');
          await reload();
          return;
        }
        if (res.data?.ok === false) setMessage('刷新失败：' + (res.data?.quotaError || res.data?.error || res.status));
        else setMessage('已刷新（' + fmtClock(Date.now()) + '）');
        reload();
      };

      const toneOf = (remain, size) => {
        const ratio = size > 0 ? remain / size : 1;
        return ratio <= 0.1 ? 'bad' : ratio <= 0.3 ? 'warn' : 'ok';
      };

      return h('div', { className: 'wb-card wb-quota' },
        h('div', { className: 'wb-quota-head' },
          h('div', { style: { minWidth: 0 } },
            h('span', { className: 'wb-quota-label' }, '积分余额'),
            h('div', { className: 'wb-quota-total' }, total === null ? '—' : fmtInt(total)),
            h('div', { className: 'wb-note', style: { margin: '2px 0 0' } },
              error
                ? '读取失败：' + error
                : (packages.length
                  ? `${packages.length} 种套餐${status?.quotaAt ? ' · 更新于 ' + fmtClock(status.quotaAt) : ''}`
                  : '还没有读到套餐明细'))),
          h('div', { className: 'wb-actions', style: { margin: 0 } },
            h(Btn, { primary: true, disabled: refreshing || busy, onClick: refreshQuota }, refreshing ? '刷新中…' : '刷新积分'),
            h(Btn, { onClick: () => onOpenTab('usage') }, '看用量'))),
        message ? h('p', { className: 'wb-note', style: { margin: '6px 0 0' } }, message) : null,
        packages.length
          ? h('div', { className: 'wb-quota-pkgs' },
            packages.map((p) => h('div', { key: p.name, className: 'wb-quota-pkg' },
              h('div', { className: 'wb-quota-pkg-head' },
                h('span', { className: 'wb-quota-pkg-name', title: p.name }, p.name + (p.count > 1 ? ' ×' + p.count : '')),
                h('span', { className: 'wb-quota-pkg-num' }, p.remain + ' / ' + p.size)),
              h('div', { className: 'wb-bar' }, h('i', { className: toneOf(p.remain, p.size), style: { width: Math.max(0, Math.min(100, p.size > 0 ? (p.remain / p.size) * 100 : 0)) + '%' } })),
              (p.monthly || p.expiresAt)
                ? h('div', { className: 'wb-note', style: { margin: '3px 0 0' } },
                  [p.monthly ? '月度' : null, p.expiresAt ? '到期 ' + p.expiresAt : null].filter(Boolean).join(' · '))
                : null)))
          : null);
    }

    // ─────────────────────────── 账号 ───────────────────────────
    function AccountsPanel({ onStartConsole, busy }) {
      const api = useConsoleApi(CONSOLE_API + '/accounts', { interval: 30000 });
      const { data, error, status, reload } = api;
      const [working, setWorking] = useState('');
      const [message, setMessage] = useState('');
      if (api.availability.state !== 'ok' && (status === 503 || status === 404)) {
        return h(ConsoleGate, { availability: api.availability, onStartConsole, onProbe: api.probeConsole, busy, feature: '账号' });
      }
      const accounts = data?.accounts || [];
      const switchTo = async (name) => {
        setWorking(name);
        setMessage('');
        const res = await postJson(CONSOLE_API + '/account/switch', { file: name });
        setWorking('');
        setMessage(res.data?.switched ? '已切换到 ' + name + '（桥已重启，两边同步）' : '切换失败：' + (res.data?.error || res.status));
        reload();
      };
      return h(Card, { title: '账号' },
        error ? h(Alert, { bad: true }, error) : null,
        message ? h(Alert, null, message) : null,
        data?.keyError ? h(Alert, null, 'AtRest 密钥获取失败：' + data.keyError + '（无法逐个验证账号可用性）') : null,
        h('p', { className: 'wb-note', style: { marginTop: 0 } }, '登录目录下存在多个账号快照时可在此切换。切换会自动重启桥、清空上一个账号的体检结论与余额缓存 —— 与控制器里点「切换」完全等价。'),
        data?.dir ? h('p', { className: 'wb-note' }, '登录目录：' + data.dir) : null,
        /* 账号是"每账号一行"的卡片式列表，不是表格。
           设置页是窄列（常见 600~700px），5~7 列的表格在这里必然被挤压 ——
           要么逐字折断、要么被卡片裁掉（用户截图里的样子）。账号通常就 2~3 个，
           列表既能容纳长域名，也不会有列宽问题。 */
        h('div', { style: { marginTop: '10px' } },
          accounts.map((a) => h('div', { key: a.name, className: 'wb-account' + (a.usable ? '' : ' bad') },
            h('div', { className: 'wb-account-head' },
              h('b', { title: a.path || a.name }, a.name),
              a.active
                ? h(Pill, { tone: 'ok', text: '使用中' })
                : h('span', { className: 'wb-status-cell' },
                  a.usable ? h(Pill, { tone: '', text: '可用' }) : h(Pill, { tone: 'bad', text: a.error ? '不可用' : '未验证' }),
                  h(Btn, { disabled: !!working || busy || !a.usable, onClick: () => switchTo(a.name), title: a.error || '' }, working === a.name ? '切换中…' : '切换'))),
            h('div', { className: 'wb-note', style: { margin: '4px 0 0' } },
              (a.account || a.userId || '(未识别账号)') + (a.domain ? ' · ' + a.domain : '')),
            h('div', { className: 'wb-note', style: { margin: '2px 0 0' } },
              '剩余 ' + (a.expiresAt ? fmtRemaining(new Date(a.expiresAt).toISOString()) : '未知')
              + ' · 凭据 ' + (a.encrypted ? 'AtRest 信封' : '明文'))))),
        // 不可用的账号把原因**写在页面上**，不要只藏在 tooltip 里
        accounts.some((a) => !a.usable)
          ? h('div', { style: { marginTop: '10px' } },
            h('p', { className: 'wb-note', style: { marginTop: 0 } }, '不可用的账号及原因：'),
            ...accounts.filter((a) => !a.usable).map((a) => h('p', { key: a.name, className: 'wb-note', style: { margin: '2px 0 0' } },
              '· ' + a.name + '：' + (a.error || '未能解开凭据（可能是另一个 build 写入的）'))))
          : null,
        h('div', { className: 'wb-actions', style: { marginTop: '10px' } }, h(Btn, { onClick: reload }, '刷新')));
    }

    // ─────────────────────────── 用量 ───────────────────────────
    function UsagePanel() {
      const [days, setDays] = useState(7);
      const [metric, setMetric] = useState('calls');
      const hours = days <= 1;
      const path = `/workbuddy/usage?days=${days}${hours ? '&hours=1' : ''}`;
      const { data, error, reload } = useJson(path, { interval: 60000 });
      // 宿主的 /workbuddy/usage 是「摊平」的（{ok, total, models, days…}）；
      // 早期版本套了一层 {usage:{…}}。两种都认，免得版本错配时表格空白。
      const usage = data && data.usage ? data.usage : data;
      const total = usage?.total || {};
      const series = hours ? (usage?.hours || []) : (usage?.days || []);
      const points = series.map((d) => ({
        label: hours ? String(d.key).slice(-2) + '时' : String(d.day || d.key).slice(5),
        value: metric === 'calls' ? d.calls : metric === 'tokens' ? (d.promptTokens || 0) + (d.completionTokens || 0) : d.credit || 0,
      }));
      const [clearing, setClearing] = useState(false);
      const [message, setMessage] = useState('');
      const clearLedger = async () => {
        // 破坏性操作，二次确认（与控制台一致）；并且必须把结果说出来，
        // 不能点了没反应（旧实现就是发完请求不检查响应）。
        if (typeof window.confirm === 'function'
          && !window.confirm('确定清空本地用量账本？\n\n只删本机的统计记录（时间/模型/耗时/token/积分），不影响上游额度与对话内容。此操作不可撤销。')) return;
        setClearing(true);
        setMessage('');
        const res = await postJson('/workbuddy/usage', undefined, 'DELETE');
        setClearing(false);
        setMessage(res.data?.ok || res.data?.cleared ? '账本已清空。' : `清空失败：${res.data?.error || 'HTTP ' + res.status}`);
        reload();
      };
      return h('div', { style: { display: 'flex', flexDirection: 'column', gap: '12px' } },
        h(Card, { title: '用量统计' },
          h('div', { className: 'wb-actions', style: { marginBottom: '10px' } },
            h('select', { className: 'wb-select', value: String(days), onChange: (e) => setDays(Number(e.target.value)) },
              h('option', { value: '1' }, '最近 24 小时'), h('option', { value: '7' }, '最近 7 天'), h('option', { value: '30' }, '最近 30 天')),
            h('select', { className: 'wb-select', value: metric, onChange: (e) => setMetric(e.target.value) },
              h('option', { value: 'calls' }, '调用次数'), h('option', { value: 'tokens' }, 'tokens'), h('option', { value: 'credit' }, '消耗积分')),
            h(Btn, { onClick: reload }, '刷新'),
            h(Btn, { onClick: () => downloadCsv('workbuddy-usage.csv',
              ['day', 'calls', 'promptTokens', 'completionTokens', 'credit'],
              series.map((d) => [d.day || d.key, d.calls, d.promptTokens, d.completionTokens, d.credit])) }, '导出 CSV'),
            h(Btn, { disabled: clearing, onClick: clearLedger }, clearing ? '清空中…' : '清空账本')),
          error ? h(Alert, { bad: true }, error) : null,
          message ? h(Alert, null, message) : null,
          h('div', { className: 'wb-grid' },
            h('div', { className: 'wb-metric' }, h('span', null, '调用'), h('b', null, fmtInt(total.calls))),
            h('div', { className: 'wb-metric' }, h('span', null, '失败'), h('b', null, fmtInt(total.failed))),
            h('div', { className: 'wb-metric' }, h('span', null, '输入 tokens'), h('b', null, fmtTokens(total.promptTokens))),
            h('div', { className: 'wb-metric' }, h('span', null, '输出 tokens'), h('b', null, fmtTokens(total.completionTokens))),
            h('div', { className: 'wb-metric' }, h('span', null, '消耗积分'), h('b', null, typeof total.credit === 'number' ? total.credit.toFixed(2) : '0')),
            h('div', { className: 'wb-metric' }, h('span', null, '平均耗时'), h('b', null, total.calls ? Math.round((total.ms || 0) / total.calls) + ' ms' : '—'))),
          h('div', { style: { marginTop: '12px' } }, h(LineChart, { points })),
          h('p', { className: 'wb-note' }, '只记元数据（时间 / 模型 / 耗时 / token / 积分），不含任何对话内容。')),
        h(Card, { title: '积分花在哪些模型上' },
          h('div', { className: 'wb-scroll' },
            h('table', { className: 'wb-table' },
              h('thead', null, h('tr', null, h('th', null, '模型'), h('th', { className: 'num' }, '次数'), h('th', { className: 'num' }, 'tokens'), h('th', { className: 'num' }, '积分'))),
              h('tbody', null, (usage?.models || []).map((m) => h('tr', { key: m.model },
                h('td', null, m.model),
                h('td', { className: 'num' }, fmtInt(m.calls)),
                h('td', { className: 'num' }, fmtTokens((m.promptTokens || 0) + (m.completionTokens || 0))),
                h('td', { className: 'num' }, typeof m.credit === 'number' ? m.credit.toFixed(2) : '0')))))),
          (usage?.failures || []).length
            ? h('div', null, h('p', { className: 'wb-note' }, '最近的失败：'),
              h('div', { className: 'wb-scroll', style: { maxHeight: '200px' } },
                h('table', { className: 'wb-table' },
                  h('thead', null, h('tr', null, h('th', null, '时间'), h('th', null, '模型'), h('th', null, '错误'))),
                  h('tbody', null, usage.failures.map((f, i) => h('tr', { key: i, className: 'bad' },
                    h('td', null, fmtClock(f.t)),
                    h('td', null, f.model),
                    h('td', { title: '点击复制', className: 'click wrap', onClick: () => copyText(String(f.error || '')) }, String(f.error || '').slice(0, 160))))))))
            : null));
    }

    // ─────────────────────────── 最近请求 ───────────────────────────
    function RequestsPanel() {
      const [limit, setLimit] = useState(40);
      const [onlyFailed, setOnlyFailed] = useState(false);
      const [modelFilter, setModelFilter] = useState('');
      const [paused, setPaused] = useState(false);
      const { data, error, reload } = useJson(`/workbuddy/requests?limit=${limit}`, { interval: paused ? 0 : 5000 });
      // 筛选下拉要用**完整目录**，不能只用当前这页里出现过的模型 ——
      // 否则换了模型之后旧模型就从下拉里消失了（筛选等于做不了）。
      const { data: directory } = useJson('/workbuddy/models', { interval: 300000 });
      const all = data?.requests || [];
      const models = useMemo(() => {
        const fromDirectory = (directory?.models || []).map((m) => m.id);
        const seen = new Set(fromDirectory);
        for (const r of all) if (r.model && !seen.has(r.model)) { seen.add(r.model); fromDirectory.push(r.model); }
        return fromDirectory;
      }, [directory, all]);
      const rows = all.filter((r) => (!onlyFailed || !r.ok) && (!modelFilter || r.model === modelFilter));
      const failLabel = (r) => `失败${r.status ? ' HTTP ' + r.status : ''}${r.code ? ' · code ' + r.code : ''}`;
      return h(Card, { title: '最近请求' },
        error ? h(Alert, { bad: true }, error) : null,
        h('div', { className: 'wb-actions', style: { marginBottom: '10px' } },
          h('select', { className: 'wb-select', value: modelFilter, onChange: (e) => setModelFilter(e.target.value) },
            h('option', { value: '' }, `全部模型（${models.length}）`),
            models.map((m) => h('option', { key: m, value: m }, m))),
          h('label', { className: 'wb-check' }, h('input', { type: 'checkbox', checked: onlyFailed, onChange: (e) => setOnlyFailed(e.target.checked) }), `仅看失败（${all.filter((r) => !r.ok).length}）`),
          h('select', { className: 'wb-select', value: String(limit), onChange: (e) => setLimit(Number(e.target.value)) },
            h('option', { value: '40' }, '40 条'), h('option', { value: '100' }, '100 条'), h('option', { value: '200' }, '200 条')),
          h('label', { className: 'wb-check' }, h('input', { type: 'checkbox', checked: paused, onChange: (e) => setPaused(e.target.checked) }), '暂停自动刷新'),
          h(Btn, { onClick: reload }, '刷新'),
          h(Btn, { onClick: () => downloadCsv('workbuddy-requests.csv',
            ['time', 'model', 'stream', 'ok', 'ms', 'promptTokens', 'completionTokens', 'credit', 'status', 'code', 'error'],
            rows.map((r) => [new Date(r.t).toISOString(), r.model, r.stream ? 1 : 0, r.ok ? 1 : 0, r.ms, r.promptTokens || 0, r.completionTokens || 0, r.credit || 0, r.status || '', r.code || '', r.error || ''])) }, '导出当前筛选 CSV')),
        h('div', { className: 'wb-scroll' },
          h('table', { className: 'wb-table' },
            h('thead', null, h('tr', null,
              h('th', null, '时间'), h('th', null, '模型'), h('th', null, '流式'), h('th', { className: 'num' }, '耗时'),
              h('th', { className: 'num' }, 'in'), h('th', { className: 'num' }, 'out'), h('th', { className: 'num' }, '积分'), h('th', null, '结果'))),
            h('tbody', null, rows.map((r, i) => h('tr', { key: i, className: r.ok ? '' : 'bad' },
              h('td', { title: fmtTime(r.t) }, fmtClock(r.t)),
              h('td', null, r.model),
              h('td', null, r.stream ? '是' : '否'),
              h('td', { className: 'num' }, fmtInt(r.ms) + ' ms'),
              h('td', { className: 'num' }, fmtTokens(r.promptTokens || 0)),
              h('td', { className: 'num' }, fmtTokens(r.completionTokens || 0)),
              h('td', { className: 'num' }, typeof r.credit === 'number' ? r.credit.toFixed(3) : '—'),
              h('td', { className: r.ok ? '' : 'click', title: r.ok ? '' : (String(r.error || '').slice(0, 300) + '\n（点击复制完整详情）'), onClick: r.ok ? undefined : () => copyText(JSON.stringify(r, null, 2)) },
                r.ok ? '成功' : failLabel(r)))))),
          !rows.length ? h('p', { className: 'wb-note' }, all.length ? '没有符合筛选条件的请求。' : '还没有请求记录。') : null));
    }

    // ─────────────────────────── 签到 ───────────────────────────
    function CheckinPanel({ onStartConsole, busy }) {
      const { data, error, reload } = useJson('/workbuddy/checkin', { interval: 600000 });
      const cstateApi = useConsoleApi(CONSOLE_API + '/checkin', { interval: 600000 });
      const { data: cstate, status: cstatus, reload: reloadState } = cstateApi;
      const [working, setWorking] = useState(false);
      const [message, setMessage] = useState('');
      // 同样兼容两种形状：{ok, status:{…}} 与早期的 {ok, todayCheckedIn…}
      const status = data && data.status ? data.status : (data || {});
      const runtime = cstate?.checkin || null;
      const consoleReady = cstateApi.availability.state === 'ok' && cstate?.ok !== false;
      const claim = async () => {
        setWorking(true);
        setMessage('');
        // 领取优先走控制台（它会在 .state.json 里记 lastAt/lastResult，两边一致）；
        // 控制台没跑（503）或宿主端旧构建（404）时退回插件自己的桥调用。
        let res = await postJson(CONSOLE_API + '/checkin', {});
        if (res.status === 503 || res.status === 404) res = await postJson('/workbuddy/checkin?claim=1', {});
        setWorking(false);
        setMessage(res.data?.ok === false ? '领取失败：' + (res.data?.error || res.status) : '已尝试领取今日签到。');
        reload(); reloadState();
      };
      const toggleAuto = async (next) => {
        setWorking(true);
        const res = await postJson(CONSOLE_API + '/checkin/settings', { auto: next });
        setWorking(false);
        setMessage(res.data?.saved
          ? '已' + (next ? '开启' : '关闭') + '自动签到（桥侧要重启桥才生效，控制器同此行为）'
          : (res.status === 404
            ? '自动签到开关由控制台写 .state.json：宿主端还是旧构建，重启一次 dsh 后再改。'
            : '设置失败：' + (res.data?.error || res.status)));
        reloadState();
      };
      return h(Card, { title: '每日签到' },
        error ? h(Alert, { bad: true }, error) : null,
        message ? h(Alert, null, message) : null,
        h(Row, { label: '今日' }, status.todayCheckedIn ? h(Pill, { tone: 'ok', text: '已签到' + (typeof status.todayCredit === 'number' ? '（+' + status.todayCredit + '）' : '') }) : h(Pill, { tone: 'warn', text: '未签到' })),
        typeof status.streakDays === 'number' ? h(Row, { label: '连续天数' }, status.streakDays + ' 天') : null,
        status.active === false ? h(Row, { label: '活动' }, '账号当前无签到活动') : null,
        runtime ? h(Row, { label: '上次尝试' }, (runtime.lastAt ? fmtTime(runtime.lastAt) + '（' + (runtime.lastSource || '?') + '）' : '—') + (runtime.lastError ? ' · ' + runtime.lastError : '')) : null,
        runtime ? h(Row, { label: '自动签到' }, h('label', { className: 'wb-check' },
          h('input', { type: 'checkbox', checked: runtime.auto !== false, disabled: working || !consoleReady, onChange: (e) => toggleAuto(e.target.checked) }),
          runtime.auto !== false ? '开启' : '关闭')) : null,
        !consoleReady ? h('p', { className: 'wb-note' }, '自动签到开关存在 .state.json，由控制台负责读写；控制台没跑时这项不可改（可先启动控制台）。') : null,
        !consoleReady && cstatus === 404 ? h(Alert, { bad: true }, '宿主端还是旧构建（重启一次 dsh 后，自动签到开关与「上次尝试」才会出现）。') : null,
        h('div', { className: 'wb-actions', style: { marginTop: '10px' } },
          h(Btn, { primary: true, disabled: working || status.todayCheckedIn === true, onClick: claim }, working ? '领取中…' : '立即领取'),
          h(Btn, { disabled: working, onClick: () => { reload(); reloadState(); } }, '刷新'),
          !consoleReady ? h(Btn, { disabled: busy, onClick: onStartConsole }, '启动控制台') : null));
    }

    // ─────────────────────────── 环境诊断 ───────────────────────────
    function DiagnosePanel({ onStartConsole, busy, status: pluginStatus }) {
      const api = useConsoleApi(CONSOLE_API + '/diagnose', { interval: 60000 });
      const { data, error, status, reload } = api;
      if (status === 503 || status === 404) {
        return h(ConsoleGate, {
          availability: api.availability,
          onStartConsole,
          onProbe: api.probeConsole,
          busy,
          feature: '环境诊断（诊断由控制台调用项目自带的 lib/diagnostics.mjs，与控制台页面同一套结论）',
        });
      }
      const items = data?.items || [];
      const summary = data?.summary || {};

      /**
       * 诊断库的「dsh 模型路由」一项用的是**迁移前**的口径：检查 settings.yaml 里
       * 有没有手写的 llm-pi-ai 路由。插件的原生路由（运行时注册）它不认识 ——
       * 旧的那段恰恰是被插件清掉的，于是永远误报 fail。
       * 这里按**运行时事实**改判：原生路由已注册 = 通过；并注明这是插件的判定。
       * （桥 / 账号等其它项与插件无冲突，照单显示。）
       */
      const adjusted = [];
      for (const item of items) {
        const isRouteItem = item.id === 'settings' || item.label === 'dsh 模型路由';
        if (isRouteItem && item.status === 'fail' && pluginStatus?.route?.registered) {
          adjusted.push({
            ...item,
            status: 'ok',
            detail: `原生 provider=${pluginStatus.route.provider}（插件运行时注册，无需 settings.yaml）`,
            hint: null,
          });
          continue;
        }
        adjusted.push(item);
      }
      const adjSummary = adjusted.reduce((acc, item) => {
        acc[item.status] = (acc[item.status] || 0) + 1;
        return acc;
      }, {});

      const tone = (s) => (s === 'ok' ? 'ok' : s === 'warn' ? 'warn' : 'bad');
      return h(Card, { title: '环境诊断' },
        error ? h(Alert, { bad: true }, error) : null,
        Object.keys(adjSummary).length
          ? h('p', { className: 'wb-note', style: { marginTop: 0 } }, `${adjSummary.ok || 0} 项通过 / ${adjSummary.warn || 0} 项警告 / ${adjSummary.fail || 0} 项失败 —— 红色项不解决，模型就不会出现。`)
          : null,
        h('div', { style: { marginTop: '8px' } }, adjusted.map((item, i) => h('div', { key: i, className: 'wb-row' },
          h('span', { style: { display: 'flex', alignItems: 'center', gap: '8px', minWidth: 0 } },
            h('span', { className: 'wb-dot ' + tone(item.status) }),
            h('span', null, h('b', null, item.label))),
          h('span', { className: 'wb-value' }, item.detail || '')))),
        h('div', { style: { marginTop: '8px' } }, adjusted.filter((i) => i.hint).map((i, k) => h('p', { key: k, className: 'wb-note' }, '建议（' + i.label + '）：' + i.hint))),
        h('div', { className: 'wb-actions', style: { marginTop: '10px' } }, h(Btn, { onClick: reload }, '重新诊断')));
    }

    // ─────────────────────────── 可用模型 / 体检 ───────────────────────────
    function ModelsPanel({ onStartConsole, busy, sampleModel, onUseModel }) {
      const [refreshTick, setRefreshTick] = useState(0);
      const { data, error, reload } = useJson(`/workbuddy/models${refreshTick ? '?refresh=1' : ''}`, { interval: 120000 });
      const probesApi = useConsoleApi(CONSOLE_API + '/probe-results', { interval: 30000 });
      const { data: probes, status: pstatus, reload: reloadProbes } = probesApi;
      const [detail, setDetail] = useState('');
      const [working, setWorking] = useState('');
      const [progress, setProgress] = useState(null);
      const [message, setMessage] = useState('');
      const models = data?.models || [];
      const results = probes?.results || {};
      // 只有确认控制台可用（availability 判定为 ok）才允许体检/清除：
      // 加载中或 404/503 时都禁用，避免对不存在的接口空点。
      const consoleReady = probesApi.availability.state === 'ok';
      const resultOf = (id) => results[id];

      // 体检与结论保存只依赖控制台：不可用时给出可行动的卡，而不是对 404 空转
      if ((pstatus === 503 || pstatus === 404) && models.length === 0) {
        return h('div', { style: { display: 'flex', flexDirection: 'column', gap: '12px' } },
          h(Card, { title: '可用模型' }, error ? h(Alert, { bad: true }, error) : h('p', { className: 'wb-note', style: { margin: 0 } }, '正在读取模型目录…')),
          h(ConsoleGate, { availability: probesApi.availability, onStartConsole, onProbe: probesApi.probeConsole, busy, feature: '模型体检' }));
      }

      const runProbe = async (scope) => {
        const targets = scope === 'all' ? models : models.filter((m) => resultOf(m.id)?.ok === false);
        if (!targets.length) { setMessage('没有需要体检的模型（"不可用"范围为空）。'); return; }
        setWorking('probe');
        setProgress({ done: 0, total: targets.length });
        const batch = {};
        let okCount = 0;
        for (let i = 0; i < targets.length; i += 1) {
          const m = targets[i];
          const res = await postJson(CONSOLE_API + '/probe', { model: m.id });
          const entry = res.data && res.data.model ? { ok: res.data.ok === true, ms: res.data.ms || 0, at: Date.now(), ...(typeof res.data.credit === 'number' ? { credit: res.data.credit } : {}), ...(res.data.error ? { error: String(res.data.error).slice(0, 200) } : {}) } : { ok: false, ms: 0, at: Date.now(), error: 'HTTP ' + res.status };
          batch[m.id] = entry;
          if (entry.ok) okCount += 1;
          setProgress({ done: i + 1, total: targets.length });
          if (res.status === 503 || res.status === 404) {
            setMessage('体检需要控制台在跑（宿主端旧构建时则需重启一次 dsh）—— 已中止，避免对不存在的接口逐个空跑。');
            break;
          }
        }
        const saved = await postJson(CONSOLE_API + '/probe-results', { results: batch, lastRun: { scope: scope === 'all' ? 'all' : 'checked', count: Object.keys(batch).length } });
        setWorking('');
        setProgress(null);
        setMessage(saved.data?.saved ? `体检完成：${okCount}/${Object.keys(batch).length} 可用（结论已存进 .state.json，控制器里看到的是同一份）` : '体检结果保存失败：' + (saved.data?.error || saved.status));
        reloadProbes();
      };
      const probeOne = async (id) => {
        setWorking(id);
        const res = await postJson(CONSOLE_API + '/probe', { model: id });
        if (res.data?.model) {
          await postJson(CONSOLE_API + '/probe-results', {
            results: { [id]: { ok: res.data.ok === true, ms: res.data.ms || 0, at: Date.now(), ...(typeof res.data.credit === 'number' ? { credit: res.data.credit } : {}), ...(res.data.error ? { error: String(res.data.error).slice(0, 200) } : {}) } },
          });
        }
        setWorking('');
        reloadProbes();
      };
      const clearProbes = async () => {
        if (typeof window.confirm === 'function' && !window.confirm('确定清除全部体检结论？\n\n只删 .state.json 里的 probe 记录（下次要重新体检），不影响模型与路由。')) return;
        const res = await postJson(CONSOLE_API + '/probe-results', undefined, 'DELETE');
        setMessage(res.data?.cleared || res.data?.ok ? '体检结论已清除。' : '清除失败：' + (res.data?.error || res.status));
        reloadProbes();
      };

      const unavailable = models.filter((m) => resultOf(m.id)?.ok === false).map((m) => m.id);
      const [probeFilter, setProbeFilter] = useState('all');
      const visible = probeFilter === 'fail'
        ? models.filter((m) => resultOf(m.id)?.ok === false)
        : probeFilter === 'untested'
          ? models.filter((m) => !resultOf(m.id))
          : models;
      return h(Card, { title: '可用模型（' + models.length + '）' },
        error ? h(Alert, { bad: true }, error) : null,
        data && data.ok === false ? h(Alert, { bad: true }, data.error) : null,
        message ? h(Alert, null, message) : null,
        h('p', { className: 'wb-note', style: { marginTop: 0 } },
          '模型列表来自桥的动态目录，**不需要勾选或保存**：选模型时 provider 选 “WorkBuddy” 就能看到全部。体检结论存在 .state.json 的 probe 字段，与控制器共用一份。'),
        models.length
          ? h('p', { className: 'wb-note' },
            `共 ${models.length} 个模型，其中 ${models.filter((m) => m.images).length} 个支持图片输入（名称旁标「图片」），`
            + `${models.filter((m) => m.free).length} 个免费；体检过的 ${models.filter((m) => resultOf(m.id)).length} 个。`)
          : null,
        h('div', { className: 'wb-actions', style: { margin: '10px 0' } },
          h(Btn, { primary: true, disabled: working === 'probe' || !consoleReady, onClick: () => runProbe('all') }, progress ? `体检中 ${progress.done}/${progress.total}` : '全部体检'),
          h(Btn, { disabled: working === 'probe' || !consoleReady || !unavailable.length, onClick: () => runProbe('checked') }, `重测不可用的（${unavailable.length}）`),
          h('select', { className: 'wb-select', value: probeFilter, onChange: (e) => setProbeFilter(e.target.value) },
            h('option', { value: 'all' }, `全部（${models.length}）`),
            h('option', { value: 'fail' }, `只看不可用（${unavailable.length}）`),
            h('option', { value: 'untested' }, `只看未测（${models.filter((m) => !resultOf(m.id)).length}）`)),
          h(Btn, { disabled: !!working, onClick: () => { setRefreshTick(refreshTick + 1); reload(); } }, '刷新目录'),
          h(Btn, { disabled: !!working || !consoleReady, onClick: clearProbes }, '清除体检结论'),
          h(Btn, { onClick: () => downloadCsv('workbuddy-models.csv',
            ['id', 'name', 'contextWindow', 'maxTokens', 'credits', 'free', 'images', 'probe', 'probeMs', 'probeError'],
            models.map((m) => [m.id, m.name, m.contextWindow || '', m.maxTokens || '', m.credits ?? '', m.free ? 1 : 0, m.images ? 1 : 0, resultOf(m.id) ? (resultOf(m.id).ok ? 'ok' : 'fail') : '', resultOf(m.id)?.ms ?? '', resultOf(m.id)?.error || ''])) }, '导出 CSV')),
        !consoleReady ? h('p', { className: 'wb-note' }, '体检需要控制台在跑（结论只由它写，保证两边一致）。') : null,
        h('div', { className: 'wb-scroll' },
          h('table', { className: 'wb-table' },
            h('thead', null, h('tr', null,
              // 列数压到 6 列：上下文与输出合并（详情里有拆分），体检列不再塞实测扣分 ——
              // 之前 7 列在设置页宽度下必然横向滚动，最后一列被压窄后按钮还会竖着堆。
              h('th', null, '模型'), h('th', null, '名称'), h('th', { className: 'num' }, '上下文 / 输出'),
              h('th', { className: 'num' }, '倍率'), h('th', null, '体检'), h('th', { className: 'wb-actions-col' }, '操作'))),
            h('tbody', null, visible.flatMap((m) => {
              const probe = resultOf(m.id);
              const open = detail === m.id;
              const rows = [h('tr', { key: m.id, className: (probe && probe.ok === false ? 'bad ' : '') + (open ? 'open' : '') },
                h('td', null, m.id + (m.id === sampleModel ? ' ★' : '')),
                h('td', null, (m.name || ''),
                  m.images ? h('span', { className: 'wb-badge', title: '支持图片输入（多模态）' }, '图片') : null,
                  badgesOf(m).map((b, bi) => h('span', {
                    key: bi,
                    className: 'wb-badge',
                    style: b.color ? { background: b.color + '22', color: b.color, borderColor: b.color + '55' } : undefined,
                  }, b.label))),
                h('td', { className: 'num' }, (m.contextWindow ? fmtTokens(m.contextWindow) : '—') + ' / ' + (m.maxTokens ? fmtTokens(m.maxTokens) : '—')),
                h('td', { className: 'num' }, m.free ? '免费' : (m.credits === null || m.credits === undefined ? '—' : String(m.credits))),
                h('td', null, probe
                  ? h(Pill, { tone: probe.ok ? 'ok' : 'bad', text: (probe.ok ? '可用' : '不可用') + ' · ' + probe.ms + 'ms' })
                  : h('span', { className: 'wb-note', style: { margin: 0 } }, '未测')),
                h('td', { className: 'wb-actions-col' },
                  h(Btn, { disabled: !!working || !consoleReady, onClick: () => probeOne(m.id), title: probe?.error || (probe && typeof probe.credit === 'number' ? '实测扣分 ' + probe.credit : '') }, working === m.id ? '测…' : '测'),
                  h(Btn, { className: open ? 'primary' : '', onClick: () => setDetail(open ? '' : m.id), title: open ? '收起详情' : '查看详情' }, open ? '收起' : '详情')))];
              // 详情**紧跟这一行**展开（而不是挂到整张表下面 —— 那会让人找不到是哪个模型的）
              if (open) {
                rows.push(h('tr', { key: m.id + ':detail', className: 'wb-detail-row' },
                  h('td', { colSpan: 6 },
                    h('div', { className: 'wb-detail' },
                      h('div', { className: 'wb-detail-grid' },
                        h(DetailItem, { label: '模型 ID', value: m.id }),
                        h(DetailItem, { label: '名称', value: m.name || '—' }),
                        h(DetailItem, { label: '厂商标识', value: m.vendor || '—', hint: '上游返回的厂商代码（单字母），不是厂商名' }),
                        h(DetailItem, { label: '上下文 / 输出', value: `${fmtInt(m.contextWindow)} / ${fmtInt(m.maxTokens)} tokens` }),
                        h(DetailItem, { label: '计费倍率', value: m.free ? '免费' : (m.credits === null || m.credits === undefined ? '未知' : String(m.credits)) }),
                        h(DetailItem, { label: '多模态', value: m.images ? '支持图片' : '纯文本' }),
                        h(DetailItem, { label: '体检', value: probe ? (probe.ok ? `可用 · ${probe.ms}ms` : `不可用 · ${probe.ms}ms`) + (typeof probe.credit === 'number' ? ` · 实测扣分 ${probe.credit}` : '') : '未测' }),
                        h(DetailItem, { label: '标签', value: tagsOf(m).join(' · ') || '—' })),
                      badgesOf(m).length
                        ? h('div', { style: { marginTop: '8px' } },
                          h('span', { className: 'wb-note', style: { margin: '0 8px 0 0' } }, '活动：'),
                          ...badgesOf(m).map((b, bi) => h('span', {
                            key: bi,
                            className: 'wb-badge',
                            style: b.color ? { background: b.color + '22', color: b.color, borderColor: b.color + '55' } : undefined,
                          }, b.label)))
                        : null,
                      probe && probe.ok === false && probe.error ? h('p', { className: 'wb-note', style: { margin: '8px 0 0' } }, '体检错误：' + probe.error) : null,
                      m.description ? h('p', { className: 'wb-note', style: { margin: '8px 0 0' } }, m.description) : null,
                      h('div', { className: 'wb-actions', style: { marginTop: '10px' } },
                        h(Btn, { onClick: () => onUseModel(m.id) }, '用这个模型对话 →'),
                        h(Btn, { onClick: () => copyText(m.id) }, '复制 ID'),
                        h(Btn, { onClick: () => setDetail('') }, '收起'))))));
              }
              return rows;
            })))),
        probes?.updatedAt ? h('p', { className: 'wb-note' }, '体检结论更新于 ' + fmtTime(probes.updatedAt) + (probes.lastRun ? `（本轮 ${probes.lastRun.count} 个，范围 ${probes.lastRun.scope}）` : '')) : null);
    }

    // ─────────────────────────── 对话测试 ───────────────────────────
    /**
     * 对话测试。
     *
     * 模型选择由容器持有（`model` / `setModel`）—— 这样切标签页回来不会被重置，
     * 也就不会给人"模型是写死的"错觉。未选时回落到推荐模型（sampleModel）。
     */
    function ChatPanel({ onStartConsole, busy, sampleModel, model, setModel, messages, setMessages }) {
      const { data: modelsData } = useJson('/workbuddy/models', { interval: 300000 });
      const models = modelsData?.models || [];
      const [input, setInput] = useState('');
      const [streaming, setStreaming] = useState(false);
      const [meta, setMeta] = useState(null);
      const [error, setError] = useState('');
      const [filter, setFilter] = useState('');
      const abortRef = useRef(null);
      const boxRef = useRef(null);
      const activeModel = model || sampleModel || models[0]?.id || '';
      const shown = filter.trim()
        ? models.filter((m) => (m.id + ' ' + (m.name || '')).toLowerCase().includes(filter.trim().toLowerCase()))
        : models;

      useEffect(() => { if (boxRef.current) boxRef.current.scrollTop = boxRef.current.scrollHeight; }, [messages, streaming]);

      const send = async () => {
        const text = input.trim();
        if (!text || streaming || !activeModel) return;
        setError('');
        setInput('');
        // 历史里丢掉"空的助手消息"（上一次失败/中断留下的占位），否则会被当成
        // 一条真正的空回复回灌给模型。
        const history = [
          ...messages.filter((m) => !(m.role === 'assistant' && !m.content)),
          { role: 'user', content: text },
        ];
        setMessages([...history, { role: 'assistant', content: '' }]);
        setStreaming(true);
        const started = Date.now();
        const ac = new AbortController();
        abortRef.current = ac;
        let usage = null;
        let finish = '';
        /** 把本轮的耗时/tokens/扣分贴到最后一条助手消息上（逐轮可查，不只看最后一轮）。 */
        const attachMeta = (extra) => {
          const turnMeta = {
            ms: Date.now() - started,
            finish: extra || finish || '',
            prompt: usage?.prompt_tokens ?? usage?.input_tokens ?? null,
            completion: usage?.completion_tokens ?? usage?.output_tokens ?? null,
            credit: typeof usage?.credit === 'number' ? usage.credit : null,
          };
          setMeta(turnMeta);
          setMessages((prev) => {
            const next = prev.slice();
            const last = next[next.length - 1];
            if (last && last.role === 'assistant') next[next.length - 1] = { ...last, meta: turnMeta };
            return next;
          });
        };
        try {
          const res = await fetch(CONSOLE_API + '/chat', {
            method: 'POST',
            headers: PANEL_HEADERS,
            body: JSON.stringify({ model: activeModel, stream: true, messages: history }),
            signal: ac.signal,
          });
          if (res.status === 503) { setError('对话测试由控制台代发（它管着流式透传）。先启动控制台。'); setStreaming(false); return; }
          if (res.status === 404) { setError('宿主端还是旧构建：重启一次 dsh 后对话测试才可用（完全退出托盘再打开）。'); setStreaming(false); return; }
          if (!res.ok || !res.body) {
            const raw = await res.text().catch(() => '');
            setError(`HTTP ${res.status}：${raw.slice(0, 200)}`);
            setStreaming(false);
            return;
          }
          const reader = res.body.getReader();
          const decoder = new TextDecoder();
          let tail = '';
          for (;;) {
            const { done, value } = await reader.read();
            if (done) break;
            tail += decoder.decode(value, { stream: true });
            const lines = tail.split('\n');
            tail = lines.pop() ?? '';
            for (const line of lines) {
              const s = line.trim();
              if (!s.startsWith('data:')) continue;
              const body = s.slice(5).trim();
              if (!body || body === '[DONE]') continue;
              let frame;
              try { frame = JSON.parse(body); } catch (e) { continue; }
              if (frame.usage) usage = frame.usage;
              const choice = frame.choices && frame.choices[0];
              if (!choice) continue;
              if (choice.finish_reason) finish = choice.finish_reason;
              const delta = choice.delta || {};
              const piece = typeof delta.content === 'string' ? delta.content : (typeof delta.reasoning_content === 'string' ? '' : '');
              if (piece) setMessages((prev) => {
                const next = prev.slice();
                const last = next[next.length - 1];
                next[next.length - 1] = { ...(last || { role: 'assistant' }), role: 'assistant', content: (last?.content || '') + piece };
                return next;
              });
            }
          }
          attachMeta();
        } catch (e2) {
          if (e2?.name !== 'AbortError') { setError(String(e2?.message || e2)); attachMeta('已中断'); }
          else attachMeta('已停止');
        } finally {
          setStreaming(false);
          abortRef.current = null;
        }
      };

      return h(Card, { title: '对话测试' },
        h('p', { className: 'wb-note', style: { marginTop: 0 } }, '会消耗你账号的额度（与控制器里的对话测试同一回事）。多轮对话带上下文，流式输出可随时停止。这里的模型只作用于本页测试。'),
        h('div', { className: 'wb-actions', style: { margin: '10px 0' } },
          h('span', { className: 'wb-label' }, '模型'),
          h('input', { className: 'wb-input', placeholder: '筛选模型…', value: filter, onChange: (e) => setFilter(e.target.value) }),
          h('select', { className: 'wb-select', value: activeModel, onChange: (e) => setModel(e.target.value) },
            shown.map((m) => h('option', { key: m.id, value: m.id }, m.id + (m.images ? ' · 多模态' : '')))),
          h('span', { className: 'wb-note', style: { margin: 0 } }, `共 ${shown.length} 个可选`),
          h(Btn, { disabled: streaming || !messages.length, onClick: () => { setMessages([]); setMeta(null); } }, '清空对话'),
          streaming ? h(Btn, { onClick: () => abortRef.current && abortRef.current.abort() }, '停止') : null),
        !models.length ? h(Alert, null, '模型目录还没读到（桥没跑或目录为空）—— 稍后会自动重试。') : null,
        h('p', { className: 'wb-note' }, '要让 agent 本身用某个模型，用 dsh 输入框旁的模型选择器（provider 选 WorkBuddy）；这里只影响本页的对话测试。'),
        error ? h(Alert, { bad: true }, error) : null,
        h('div', { className: 'wb-chat', ref: boxRef },
          messages.length
            ? messages.map((m, i) => h('div', { key: i, className: 'wb-msg ' + m.role },
              m.content || (streaming && i === messages.length - 1 ? '…' : ''),
              m.meta ? h('span', { className: 'wb-msg-meta' },
                `${m.meta.ms} ms · ${m.meta.finish || '?'}` +
                (m.meta.prompt !== null || m.meta.completion !== null ? ` · tokens ${m.meta.prompt ?? '?'} → ${m.meta.completion ?? '?'}` : '') +
                (m.meta.credit !== null ? ` · 扣分 ${m.meta.credit}` : '')) : null))
            : h('p', { className: 'wb-note', style: { margin: 0 } }, '还没有对话。')),
        meta ? h('p', { className: 'wb-note' }, `最近一轮：${meta.ms} ms · ${meta.finish || '?'} · tokens ${meta.prompt ?? '?'} → ${meta.completion ?? '?'}` + (meta.credit !== null ? ` · 扣分 ${meta.credit}` : '')) : null,
        h('textarea', { className: 'wb-textarea', value: input, placeholder: '输入消息，Enter 发送（Shift+Enter 换行）', onChange: (e) => setInput(e.target.value), onKeyDown: (e) => { if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); send(); } } }),
        h('div', { className: 'wb-actions', style: { marginTop: '8px' } },
          h(Btn, { primary: true, disabled: streaming || !input.trim() || !activeModel, onClick: send }, streaming ? '生成中…' : '发送')));
    }

    // ─────────────────────────── 桥日志 ───────────────────────────
    function LogPanel({ status }) {
      const [lines, setLines] = useState(200);
      const [keyword, setKeyword] = useState('');
      const [onlyError, setOnlyError] = useState(false);
      const [currentOnly, setCurrentOnly] = useState(false);
      const [paused, setPaused] = useState(false);
      const { data, error, reload } = useJson(`/workbuddy/log?lines=${lines}`, { interval: paused ? 0 : 5000 });
      const [clearing, setClearing] = useState(false);
      const [message, setMessage] = useState('');
      let all = data?.lines || [];
      const totalLines = all.length;
      // 只看本次启动：桥每次启动都会打一行 "listening on …"，取最后一处之后的内容
      if (currentOnly) {
        let idx = -1;
        all.forEach((l, i) => { if (/listening on /.test(l)) idx = i; });
        if (idx >= 0) all = all.slice(idx);
      }
      if (onlyError) all = all.filter((l) => /error|fail|refused|EADDR|invalid|401|403|429|5\d\d/i.test(l));
      if (keyword.trim()) all = all.filter((l) => l.toLowerCase().includes(keyword.trim().toLowerCase()));
      const clearLog = async () => {
        // 破坏性操作：先确认，再把结果说出来（旧实现点了没反应）
        if (typeof window.confirm === 'function'
          && !window.confirm('确定清空桥日志？\n\n只截断本机的 bridge.log（追踪问题用的历史会丢），不影响桥的运行。')) return;
        setClearing(true);
        setMessage('');
        const res = await postJson('/workbuddy/log', undefined, 'DELETE');
        setClearing(false);
        setMessage(res.data?.ok || res.data?.cleared ? '日志已清空。' : `清空失败：${res.data?.error || 'HTTP ' + res.status}`);
        reload();
      };
      return h(Card, { title: '桥日志' },
        error ? h(Alert, { bad: true }, error) : null,
        message ? h(Alert, null, message) : null,
        h('div', { className: 'wb-actions', style: { marginBottom: '10px' } },
          h('input', { className: 'wb-input', placeholder: '过滤关键字…', value: keyword, onChange: (e) => setKeyword(e.target.value) }),
          h('label', { className: 'wb-check' }, h('input', { type: 'checkbox', checked: onlyError, onChange: (e) => setOnlyError(e.target.checked) }), '只看错误'),
          h('label', { className: 'wb-check' }, h('input', { type: 'checkbox', checked: currentOnly, onChange: (e) => setCurrentOnly(e.target.checked) }), '只看本次启动'),
          h('label', { className: 'wb-check' }, h('input', { type: 'checkbox', checked: paused, onChange: (e) => setPaused(e.target.checked) }), '暂停自动刷新'),
          h('select', { className: 'wb-select', value: String(lines), onChange: (e) => setLines(Number(e.target.value)) },
            h('option', { value: '100' }, '100 行'), h('option', { value: '200' }, '200 行'), h('option', { value: '500' }, '500 行')),
          h(Btn, { onClick: reload }, '刷新'),
          h(Btn, { onClick: () => copyText(all.join('\n')) }, '复制当前视图'),
          h(Btn, { disabled: clearing, onClick: clearLog }, clearing ? '清空中…' : '清空日志')),
        h('p', { className: 'wb-note', style: { marginTop: 0 } },
          `显示 ${all.length} / ${totalLines} 行${data?.path ? ' · ' + data.path : ''}${data?.mtime ? '（更新于 ' + fmtTime(data.mtime) + '）' : ''}`),
        h('pre', { className: 'wb-log' }, all.length ? all.join('\n') : '（没有匹配的日志行）'),
        status?.bridge?.state !== 'running' ? h('p', { className: 'wb-note' }, '桥当前没在运行：日志里最后那几行通常就是它退出的原因。') : null);
    }

    // ─────────────────────────── 容器 ───────────────────────────
    const TABS = [
      { id: 'overview', label: '概览' },
      { id: 'accounts', label: '账号' },
      { id: 'usage', label: '用量' },
      { id: 'requests', label: '请求' },
      { id: 'checkin', label: '签到' },
      { id: 'diagnose', label: '诊断' },
      { id: 'models', label: '模型' },
      { id: 'chat', label: '对话测试' },
      { id: 'log', label: '日志' },
    ];

    function WorkBuddyPanel() {
      const [tab, setTab] = useState('overview');
      const [busy, setBusy] = useState(false);
      const [error, setError] = useState('');
      const [toast, setToast] = useState('');
      // 对话测试的模型与消息由容器持有：切标签页回来不丢，也不会让人以为"模型写死了"
      const [chatModel, setChatModel] = useState('');
      const [chatMessages, setChatMessages] = useState([]);
      const { data: status, reload: reloadStatus } = useJson('/workbuddy/status', { interval: 8000 });

      const act = useCallback(async (action) => {
        setBusy(true);
        setError('');
        try {
          if (action === 'start' || action === 'stop' || action === 'restart') {
            const res = await postJson('/workbuddy/bridge', { action });
            if (!res.data?.ok) setError('桥操作失败：' + (res.data?.result?.error || res.data?.error || res.status));
          } else if (action === 'console-start') {
            const res = await postJson('/workbuddy/console', { action: 'start' });
            if (!res.data?.ok) setError('控制台启动失败：' + (res.data?.result?.error || res.data?.error || res.status));
            else setToast('控制台已就绪：' + (res.data?.url || ''));
          } else if (action === 'cleanup') {
            const res = await postJson('/workbuddy/migrate', {});
            setToast(res.data?.ok ? '旧路由已清理（带备份）' : '清理失败：' + (res.data?.error || res.status));
          }
        } catch (e) {
          setError(String(e?.message || e));
        } finally {
          setBusy(false);
          reloadStatus();
        }
      }, [reloadStatus]);
      const startConsole = useCallback(() => act('console-start'), [act]);

      useEffect(() => { if (!toast) return undefined; const t = setTimeout(() => setToast(''), 4000); return () => clearTimeout(t); }, [toast]);

      const con = status?.console || {};
      const panelProps = { status, onAct: act, busy, reload: reloadStatus, onStartConsole: startConsole, onOpenTab: setTab, sampleModel: status?.sampleModel };
      return h('div', { className: 'wb-root' },
        h('div', { className: 'wb-head' },
          h('div', null,
            h('h3', { className: 'wb-title' }, 'WorkBuddy'),
            h('p', { className: 'wb-sub' },
              '插件负责引擎（原生模型路由、桥与控制台的启停），这里提供控制台的全部数据与操作；'
              + '两边共用同一个桥与同一份 .state.json，改哪边另一边的结果都一样。')),
          h('div', { className: 'wb-actions' },
            status?.bridge?.state === 'running' ? h(Pill, { tone: 'ok', text: '桥运行中' })
              : status?.bridge?.state === 'degraded' ? h(Pill, { tone: 'warn', text: '桥凭据异常' })
                : h(Pill, { tone: 'bad', text: '桥未运行' }),
            con.state === 'running' ? h(Pill, { tone: 'ok', text: '控制台运行中' }) : h(Pill, { tone: 'warn', text: '控制台未运行' }))),
        error ? h(Alert, { bad: true }, error) : null,
        toast ? h(Alert, null, toast) : null,
        h('div', { className: 'wb-tabs' }, TABS.map((t) => h('button', {
          key: t.id,
          className: 'wb-tab' + (tab === t.id ? ' on' : ''),
          onClick: () => setTab(t.id),
        }, t.label))),
        !status ? h(Card, null, '正在读取状态…') : null,
        status && tab === 'overview' ? h(OverviewPanel, panelProps) : null,
        tab === 'accounts' ? h(AccountsPanel, { onStartConsole: startConsole, busy }) : null,
        tab === 'usage' ? h(UsagePanel, null) : null,
        tab === 'requests' ? h(RequestsPanel, null) : null,
        tab === 'checkin' ? h(CheckinPanel, { onStartConsole: startConsole, busy }) : null,
        tab === 'diagnose' ? h(DiagnosePanel, { onStartConsole: startConsole, busy, status }) : null,
        tab === 'models' ? h(ModelsPanel, {
          onStartConsole: startConsole,
          busy,
          sampleModel: status?.sampleModel,
          // 「用这个模型对话 →」：把模型塞进对话测试并切过去（状态由容器持有）
          onUseModel: (id) => { setChatModel(id); setTab('chat'); },
        }) : null,
        tab === 'chat' ? h(ChatPanel, {
          onStartConsole: startConsole,
          busy,
          sampleModel: status?.sampleModel,
          model: chatModel,
          setModel: setChatModel,
          messages: chatMessages,
          setMessages: setChatMessages,
        }) : null,
        tab === 'log' ? h(LogPanel, { status }) : null);
    }

    /**
     * 客户端插件入口：把一个设置页注册进 `settings.section`。
     *
     * 三条都跟核心插件（`dsh-client-ui-settings-models` 等）逐字对齐，别凭感觉改：
     *   1. `exports.inject = ['slots']` 是**模块级导出**的 cordis 服务依赖 ——
     *      少了它，纤维会在 slots 就绪前就跑起来；
     *   2. 注册项的槽位键是 **`name`**（不是 `key`：`key` 是 keyed 槽的派发键）；
     *   3. 注册要包在 `ctx.slots.inject('<槽位>', …)` 里 —— 等这个槽被声明之后再注册，
     *      否则「注册一个还没声明的槽」会直接抛错、整个纤维失败（面板就静默消失了）。
     */
    function apply(ctx) {
      const slots = ctx.slots || (typeof ctx.get === 'function' ? ctx.get('slots') : undefined);
      if (!slots || typeof slots.register !== 'function') {
        try { console.error('dsh-plugin-workbuddy: slots service unavailable, panel not registered'); } catch (e) { /* ignore */ }
        return;
      }
      ctx.effect(() => {
        const disposeStyles = insertStyles();
        const disposeSlot = slots.inject('settings.section', () => slots.register({
          name: 'settings.section',
          id: 'workbuddy',
          order: 60,
          label: 'WorkBuddy',
        }, WorkBuddyPanel));
        return () => { disposeSlot(); disposeStyles(); };
      }, 'workbuddy.panel');
    }

    exports.name = 'workbuddy-client';
    exports.apply = apply;
    exports.inject = ['slots'];
    exports.WorkBuddyPanel = WorkBuddyPanel;
    return module.exports;
  },
});
